### ISSUE TITLE
Can't Build the package

### ISSUE THREAD

**Issue by pradeepsh2203** [Kartiksaini001/Vichesta-Takshak-2021#1]
I have installed all the dependencies mentioned in the repository but getting a error while running catkin_make and can't find what to do,So please help,Here is the screenshot.
![image](https://user-images.githubusercontent.com/68096528/133603394-cdfec146-3b06-471d-a9cb-2d4e0c60ff35.png)

**Comment by Kartiksaini001** [comment]
As it is mentioned in the error, you need to run catkin_make command from the root of workspace. You need to have a catkin workspace first, then copy the takshak folder inside the src folder of your workspace and then from the root folder of the workspace you need to run catkin_make.

**Comment by pradeepsh2203** [comment]
Thanks for your help, I was able to build the package with catkin_make but roslaunch is still not working It's saying that the world1.launch is not a launch file.
![image](https://user-images.githubusercontent.com/68096528/133878898-f86a54bc-f118-42d5-acad-737b0fdc4773.png)

**Comment by Kartiksaini001** [comment]
You might need to source your devel/setup.bash file. This needs to be done everytime you run the build command, so you can check out this link to know more about this https://answers.ros.org/question/206876/how-often-do-i-need-to-source-setupbash/ 

You should add the path and workspace name according to your folder structure.
