### ISSUE TITLE
Query regarding world

### ISSUE THREAD

**Issue by kvkpraneeth** [Kartiksaini001/Vichesta-Takshak-2021#2]
Is the world1 going to be the same world for the final assessment? 
Can we modify the bot urdf?
What about the co-ordinates of the marked region for the bot to travel to?

**Comment by Kartiksaini001** [comment]
> Is the world1 going to be the same world for the final assessment?
> Can we modify the bot urdf?
> What about the co-ordinates of the marked region for the bot to travel to?

In the final testing, only the number of balls can vary.
For urdf, you can only change the camera orientation.
There are no specific coordinates for the marked region, but it will remain sufficiently inside the camera field of view.
